#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import print_function
import argparse
from psas_packet import io

parser = argparse.ArgumentParser(prog='log2csv')
parser.add_argument('logfile', type=argparse.FileType('rb'), help="log file to read")
args = vars(parser.parse_args())

io.log2csv(args['logfile'])
